{"name":"Wingtip Sales Data","description":"A dataflow to extract, clean and prepare data to analyze Wingtip sales performance. ","version":"1.0","culture":"en-US","modifiedTime":"2020-02-17T22:49:57.4758105+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"Customers":{"queryId":"25613d37-ca3e-413a-bea9-b864ef3278a5","queryName":"Customers","loadEnabled":true},"Sales":{"queryId":"9bd3b32c-fcba-4b24-9dcc-52ab37014125","queryName":"Sales","loadEnabled":true},"Orders":{"queryId":"f8f678bc-a3c2-4dce-a503-bb2989abe725","queryName":"Orders","loadEnabled":true},"Products":{"queryId":"eaf9ddbf-3ccc-4231-8336-dd3ff790b0ca","queryName":"Products","loadEnabled":true}},"document":"section Section1;\r\nshared Customers = let\r\n  Source = Sql.Database(\"cpt.database.windows.net\", \"WingtipSalesDB\"),\r\n  Navigation = Source{[Schema = \"dbo\", Item = \"Customers\"]}[Data],\r\n  #\"Choose columns\" = Table.SelectColumns(Navigation, {\"CustomerId\", \"FirstName\", \"LastName\", \"City\", \"State\", \"Zipcode\", \"Gender\", \"BirthDate\", \"FirstPurchaseDate\", \"LastPurchaseDate\"}),\r\n  #\"Merged columns\" = Table.CombineColumns(#\"Choose columns\", {\"FirstName\", \"LastName\"}, Combiner.CombineTextByDelimiter(\" \", QuoteStyle.None), \"Customer\"),\r\n  #\"Replaced Female Values\" = Table.ReplaceValue(#\"Merged columns\", \"F\", \"Female\", Replacer.ReplaceText, {\"Gender\"}),\r\n  #\"Replaced Male Values\" = Table.ReplaceValue(#\"Replaced Female Values\", \"M\", \"Make\", Replacer.ReplaceText, {\"Gender\"}),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Replaced Male Values\", {{\"BirthDate\", type date}, {\"FirstPurchaseDate\", type date}, {\"LastPurchaseDate\", type date}}),\r\n  #\"Inserted conditional column\" = Table.AddColumn(#\"Changed column type\", \"Customer Type\", each if [FirstPurchaseDate] = [LastPurchaseDate] then \"One-time Customer\" else \"Repeat Customer\"),\r\n  #\"Removed columns\" = Table.RemoveColumns(#\"Inserted conditional column\", {\"FirstPurchaseDate\", \"LastPurchaseDate\"}),\r\n  #\"Changed column type 1\" = Table.TransformColumnTypes(#\"Removed columns\", {{\"Customer Type\", type text}})\r\nin\r\n  #\"Changed column type 1\";\r\nshared Sales = let\r\n  Source = Sql.Database(\"cpt.database.windows.net\", \"WingtipSalesDB\"),\r\n  #\"Navigation 1\" = Source{[Schema = \"dbo\", Item = \"InvoiceDetails\"]}[Data],\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Navigation 1\", {{\"SalesAmount\", Currency.Type}}),\r\n  #\"Expanded Invoices\" = Table.ExpandRecordColumn(#\"Changed column type\", \"Invoices\", {\"InvoiceDate\", \"CustomerId\"}, {\"InvoiceDate\", \"CustomerId\"}),\r\n  #\"Changed column type 1\" = Table.TransformColumnTypes(#\"Expanded Invoices\", {{\"InvoiceDate\", type date}}),\r\n  #\"Expanded Products\" = Table.ExpandRecordColumn(#\"Changed column type 1\", \"Products\", {\"UnitCost\"}, {\"UnitCost\"}),\r\n  ChangedUnitCostType = Table.TransformColumnTypes(#\"Expanded Products\", {{\"UnitCost\", Currency.Type}}),\r\n  AddProductCostColum = Table.AddColumn(ChangedUnitCostType, \"ProductCost\", each [Quantity] * [UnitCost]),\r\n  #\"Changed column type 2\" = Table.TransformColumnTypes(AddProductCostColum, {{\"ProductCost\", Currency.Type}}),\r\n  #\"Removed columns\" = Table.RemoveColumns(#\"Changed column type 2\", {\"UnitCost\"})\r\nin\r\n  #\"Removed columns\";\r\nshared Orders = let\r\n  Source = Sql.Database(\"cpt.database.windows.net\", \"WingtipSalesDB\"),\r\n  #\"Navigation 1\" = Source{[Schema = \"dbo\", Item = \"Invoices\"]}[Data],\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Navigation 1\", {\"InvoiceId\", \"InvoiceType\"}),\r\n  #\"Replaced value\" = Table.ReplaceValue(#\"Choose columns\", \"InPerson\", \"Store Purchases\", Replacer.ReplaceText, {\"InvoiceType\"}),\r\n  #\"Replaced value 1\" = Table.ReplaceValue(#\"Replaced value\", \"MailOrder\", \"Mail Order Purchases\", Replacer.ReplaceText, {\"InvoiceType\"}),\r\n  #\"Replaced value 2\" = Table.ReplaceValue(#\"Replaced value 1\", \"Online\", \"Online Purchases\", Replacer.ReplaceText, {\"InvoiceType\"})\r\nin\r\n  #\"Replaced value 2\";\r\nshared Products = let\r\n  Source = Sql.Database(\"cpt.database.windows.net\", \"WingtipSalesDB\"),\r\n  #\"Navigation 1\" = Source{[Schema = \"dbo\", Item = \"Products\"]}[Data],\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Navigation 1\", {\"ProductId\", \"Title\", \"Description\", \"ProductCategory\", \"UnitCost\", \"ListPrice\", \"ProductImageUrl\"}),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Choose columns\", {{\"Title\", \"Product\"}}),\r\n  #\"Split column by delimiter\" = Table.SplitColumn(#\"Renamed columns\", \"ProductCategory\", Splitter.SplitTextByDelimiter(\" > \"), {\"ProductCategory.1\", \"ProductCategory.2\"}),\r\n  #\"Renamed columns 1\" = Table.RenameColumns(#\"Split column by delimiter\", {{\"ProductCategory.1\", \"Category\"}, {\"ProductCategory.2\", \"Subcategory\"}})\r\nin\r\n  #\"Renamed columns 1\";\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"Customers","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Customers.csv"},"attributes":[{"name":"CustomerId","dataType":"int64"},{"name":"Customer","dataType":"string"},{"name":"City","dataType":"string"},{"name":"State","dataType":"string"},{"name":"Zipcode","dataType":"string"},{"name":"Gender","dataType":"string"},{"name":"BirthDate","dataType":"date"},{"name":"Customer Type","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2020-02-17T22:50:32.0912835+00:00","location":"https://wabieus2bpcdsap1.blob.core.windows.net:443/5ff84f87-79ac-4b9c-9842-e6bcfac10078/Customers.csv?snapshot=2020-02-17T22%3A50%3A32.0926201Z"}]},{"$type":"LocalEntity","name":"Sales","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Sales.csv"},"attributes":[{"name":"Id","dataType":"int64"},{"name":"Quantity","dataType":"int64"},{"name":"SalesAmount","dataType":"decimal"},{"name":"InvoiceId","dataType":"int64"},{"name":"ProductId","dataType":"int64"},{"name":"InvoiceDate","dataType":"date"},{"name":"CustomerId","dataType":"int64"},{"name":"ProductCost","dataType":"decimal"}],"partitions":[{"name":"Part001","refreshTime":"2020-02-17T22:51:03.2166947+00:00","location":"https://wabieus2bpcdsap1.blob.core.windows.net:443/5ff84f87-79ac-4b9c-9842-e6bcfac10078/Sales.csv?snapshot=2020-02-17T22%3A51%3A03.1602101Z"}]},{"$type":"LocalEntity","name":"Orders","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Orders.csv"},"attributes":[{"name":"InvoiceId","dataType":"int64"},{"name":"InvoiceType","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2020-02-17T22:51:34.3264849+00:00","location":"https://wabieus2bpcdsap1.blob.core.windows.net:443/5ff84f87-79ac-4b9c-9842-e6bcfac10078/Orders.csv?snapshot=2020-02-17T22%3A51%3A34.3269022Z"}]},{"$type":"LocalEntity","name":"Products","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Products.csv"},"attributes":[{"name":"ProductId","dataType":"int64"},{"name":"Product","dataType":"string"},{"name":"Description","dataType":"string"},{"name":"Category","dataType":"string"},{"name":"Subcategory","dataType":"string"},{"name":"UnitCost","dataType":"double"},{"name":"ListPrice","dataType":"double"},{"name":"ProductImageUrl","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2020-02-17T22:52:05.5876989+00:00","location":"https://wabieus2bpcdsap1.blob.core.windows.net:443/5ff84f87-79ac-4b9c-9842-e6bcfac10078/Products.csv?snapshot=2020-02-17T22%3A52%3A05.5796673Z"}]}],"relationships":[{"$type":"SingleKeyRelationship","fromAttribute":{"entityName":"Customers","attributeName":"CustomerId"},"toAttribute":{"entityName":"Sales","attributeName":"CustomerId"}},{"$type":"SingleKeyRelationship","fromAttribute":{"entityName":"Orders","attributeName":"InvoiceId"},"toAttribute":{"entityName":"Sales","attributeName":"InvoiceId"}},{"$type":"SingleKeyRelationship","fromAttribute":{"entityName":"Products","attributeName":"ProductId"},"toAttribute":{"entityName":"Sales","attributeName":"ProductId"}}]}